### Test if server is active
GET  http://localhost:5000/ 

### Get All Books
GET http://localhost:5000/api/books

### Get a particular Book
GET http://localhost:5000/api/books/3

### Add a new Book
POST http://localhost:5000/api/books
Content-Type: application/json

{
  "title": "Clean Code",
  "author": "Robert C. Martin",
  "description": "A Handbook of Agile Software Craftsmanship"
}